create type public.school_section as enum ('nursery', 'primary', 'secondary');

create table public.classes (
  id bigint generated by default as identity primary key,
  name text not null,
  section public.school_section not null,
  tuition_fee numeric(12, 2) not null default 0 check (tuition_fee >= 0)
);

create table public.students (
  id uuid primary key default gen_random_uuid(),
  reg_number text not null unique,
  full_name text not null,
  class_id bigint not null references public.classes(id) on delete restrict,
  access_pin text not null
);

create table public.results (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students(id) on delete cascade,
  session text not null,
  term text not null,
  pdf_url text,
  created_at timestamptz not null default now(),
  unique (student_id, session, term)
);

create table public.books (
  id uuid primary key default gen_random_uuid(),
  class_id bigint not null references public.classes(id) on delete cascade,
  subject text not null,
  book_title text not null,
  author text not null
);

alter table public.classes enable row level security;
alter table public.students enable row level security;
alter table public.results enable row level security;
alter table public.books enable row level security;

create policy "Anyone can view classes" on public.classes for select using (true);
create policy "Anyone can view books" on public.books for select using (true);
create policy "Authenticated staff manage classes" on public.classes for all to authenticated using (true) with check (true);
create policy "Authenticated staff manage books" on public.books for all to authenticated using (true) with check (true);
create policy "Authenticated staff manage students" on public.students for all to authenticated using (true) with check (true);
create policy "Authenticated staff manage results" on public.results for all to authenticated using (true) with check (true);

-- Result lookups should run through a server-side action so access_pin is never public.
create or replace function public.lookup_result(lookup_reg_number text, lookup_session text, lookup_term text, lookup_pin text)
returns table (student_name text, class_name text, session text, term text, pdf_url text)
language sql security definer set search_path = public
as $$
  select s.full_name, c.name, r.session, r.term, r.pdf_url
  from public.results r
  join public.students s on s.id = r.student_id
  join public.classes c on c.id = s.class_id
  where s.reg_number = lookup_reg_number and s.access_pin = lookup_pin
    and r.session = lookup_session and r.term = lookup_term;
$$;
grant execute on function public.lookup_result(text, text, text, text) to anon, authenticated;